apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pyspark
  name: pyspark
  namespace: pyspark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyspark
  template:
    metadata:
      labels:
        app: pyspark
    spec:
      containers:
      - image: pyspark_tutor:v1
        name: pyspark
        ports:
        - containerPort: 80
          name: pyspark